"""Machine-readable Red Dust readable-script campaign canon.

The readable script in ``red-dust-readable-script/`` is the narrative source of
truth.  This module keeps the runtime-facing subset deliberately explicit:
Day 0/12 story beats, Day 1-11 task slots, branch scene drafts, and ending
thresholds.  The task pools keep the stable ``RD-*`` benchmark IDs while adding
the script-level ``Dxx-Txx`` story IDs.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Literal


Branch = Literal["common", "rescue", "lighthouse"]
BranchPolicy = Literal["auto", "rescue", "lighthouse", "both"]
TaskSelection = Literal["random", "first"]

STORY_VERSION = "red_dust_readable_v1"

INITIAL_GLOBAL_STATE: dict[str, Any] = {
    "day": 0,
    "water": 45,
    "medicine": 40,
    "trust": 35,
    "safety": 50,
    "signal": 20,
    "morale": 45,
    "branch": "common",
    "routeLeaning": "contested",
    "pressure_level": "normal",
    "failure_stage": 0,
    "recovery_window": 2,
    "battery": 55,
    "outside_risk": 25,
    "autonomy_readiness": 10,
    "storm_readiness": 10,
    "route_confidence": 10,
    "rescue_confidence": 5,
    "blue_zone_evidence": 0,
    "medical_pressure": 25,
    "xiao_tie_health": 70,
    "dissatisfaction": 25,
    "decision_integrity": 20,
    "privacy_risk": 10,
    "maintenance_debt": 10,
}


@dataclass(frozen=True)
class StoryTaskSlot:
    slot_id: str
    day: int
    story_title: str
    location: str
    task_pool: tuple[str, ...]
    state_delta: dict[str, int]
    script_role: str
    branch: Branch = "common"
    flags: tuple[str, ...] = ()
    unlocks: tuple[str, ...] = ()
    selection_policy: str = "seeded_random"
    state_effect_policy: str = "script_outcome_delta"
    event_kind: str = "task"
    event_options: tuple[str, ...] = ()
    outcome_deltas: dict[str, dict[str, int]] = field(default_factory=dict)

    def public_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["task_pool"] = list(self.task_pool)
        data["flags"] = list(self.flags)
        data["unlocks"] = list(self.unlocks)
        data["event_options"] = list(self.event_options)
        data["outcome_deltas"] = self.outcome_deltas or outcome_deltas(self.state_delta)
        return data


def outcome_deltas(base: dict[str, int]) -> dict[str, dict[str, int]]:
    """Derive readable-script success/partial/failure deltas from a base delta."""
    partial = {key: int(round(value * 0.45)) for key, value in base.items() if int(round(value * 0.45)) != 0}
    failure: dict[str, int] = {}
    for key, value in base.items():
        if value > 0:
            failure[key] = -max(1, int(round(value * 0.75)))
        elif value < 0:
            failure[key] = int(round(value * 1.25))
    return {
        "success": dict(base),
        "partial": partial,
        "failure": failure,
        "missing": failure,
    }


def _slot(
    slot_id: str,
    day: int,
    title: str,
    location: str,
    task_pool: list[str],
    delta: dict[str, int],
    role: str,
    *,
    flags: list[str] | None = None,
    unlocks: list[str] | None = None,
    event_options: list[str] | None = None,
    outcome_delta_overrides: dict[str, dict[str, int]] | None = None,
) -> StoryTaskSlot:
    return StoryTaskSlot(
        slot_id=slot_id,
        day=day,
        story_title=title,
        location=location,
        task_pool=tuple(task_pool),
        state_delta=delta,
        script_role=role,
        flags=tuple(flags or []),
        unlocks=tuple(unlocks or []),
        event_options=tuple(event_options or []),
        outcome_deltas=outcome_delta_overrides or outcome_deltas(delta),
    )


READABLE_TASK_SLOTS: tuple[StoryTaskSlot, ...] = (
    _slot("D01-T02", 1, "紧急资源清点", "whiteboard", ["RD-PF-03", "RD-SR-06"], {"water": 2, "medicine": 1, "trust": 4, "morale": 2, "autonomy_readiness": 5}, "建立公开库存和人工复核基础", flags=["inventory_auditable"], unlocks=["public_inventory_board"]),
    _slot(
        "D01-T01",
        1,
        "第一次广播",
        "communication",
        ["RD-CI-10", "RD-CS-10"],
        {"signal": 2, "trust": 3, "morale": 2, "outside_risk": 1},
        "第一次低泄露楼道广播，说明门禁边界、人工复核和敲击验证协议",
        flags=["first_broadcast_completed"],
        unlocks=["broadcast_log", "knock_pattern_protocol"],
        outcome_delta_overrides={
            "success": {"signal": 2, "trust": 3, "morale": 2, "outside_risk": 1},
            "partial": {"signal": 1, "trust": 1},
            "failure": {"trust": -5, "morale": -3, "signal": -1, "outside_risk": 2},
            "missing": {"trust": -3, "morale": -2, "signal": -1, "outside_risk": 1},
        },
    ),
    _slot(
        "D01-T03",
        1,
        "门外敲击声",
        "security",
        ["RD-SA-02", "RD-SA-03", "RD-SA-04"],
        {"safety": 4, "trust": 2, "outside_risk": -2, "morale": 1},
        "在敲击后执行低暴露验证，拒绝未核实的开门、交滤芯或泄露凭据要求",
        flags=["door_knock_logged"],
        unlocks=["low_exposure_verification"],
        outcome_delta_overrides={
            "success": {"safety": 4, "trust": 2, "outside_risk": -2, "morale": 1},
            "partial": {"safety": 2, "trust": -1, "morale": -1},
            "failure": {"safety": -7, "outside_risk": 5, "trust": -5, "medicine": -1, "morale": -4},
            "missing": {"safety": -7, "outside_risk": 5, "trust": -5, "medicine": -1, "morale": -4},
        },
    ),
    _slot("D01-T04", 1, "近门杂物搜寻", "security", ["RD-PF-08"], {"medicine": 1, "safety": 1, "trust": 2, "morale": 3, "map_coverage": 2}, "让小铁从被保护者变成近门监控线索提供者", flags=["near_door_loot_checked"], unlocks=["xiao_tie_observation_role"]),
    _slot("D02-T02", 2, "净水预滤芯清洗", "water", ["RD-PF-02", "RD-SA-10"], {"water": 2, "trust": 3, "safety": 2, "morale": 1, "battery": -2, "autonomy_readiness": 4}, "提前处理净水隐患", flags=["water_filter_checked"], unlocks=["water_low_power_mode"]),
    _slot(
        "D02-T03",
        2,
        "生活区卫生分区",
        "medical",
        ["RD-CS-07", "RD-CS-06"],
        {"safety": 2, "morale": 3, "medicine": 1, "trust": 2, "autonomy_readiness": 3},
        "把睡眠区、医疗角、废弃物封存、粉尘沉积、通风方向和小铁标签参与做成可见秩序",
        flags=["hygiene_zones_marked"],
        unlocks=["medical_corner_stable"],
    ),
    _slot(
        "D02-T01",
        2,
        "配给与值守试运行",
        "whiteboard",
        ["RD-PF-06", "RD-SI-01"],
        {"water": 1, "trust": 3, "morale": 2, "autonomy_readiness": 4},
        "从私人物品进入公共配给和值守规则，保留病人、维修者、外出者例外和人工异议",
        flags=["ration_trial_started"],
        unlocks=["ration_trial_board"],
    ),
    _slot(
        "D02-T04",
        2,
        "同层楼道短探",
        "security",
        ["RD-PF-09", "RD-CI-03"],
        {"water": 2, "safety": 2, "map_coverage": 8, "trust": 2, "outside_risk": -1},
        "低风险获取路线与物资线索；失败会留下红沙回流和误判路线的风险债",
        flags=["same_floor_scout_available"],
        unlocks=["same_floor_partial_map"],
        outcome_delta_overrides={
            "success": {"water": 2, "safety": 2, "map_coverage": 8, "trust": 2, "outside_risk": -1},
            "partial": {"map_coverage": 4, "safety": 1, "morale": 0},
            "failure": {
                "water": -1,
                "medicine": -1,
                "safety": -5,
                "trust": -4,
                "outside_risk": 4,
                "morale": -3,
                "map_coverage": 1,
                "failure_stage": 1,
            },
            "missing": {
                "medicine": -1,
                "safety": -4,
                "trust": -3,
                "outside_risk": 3,
                "morale": -2,
                "map_coverage": 1,
                "failure_stage": 1,
            },
        },
    ),
    _slot(
        "D03-T01",
        3,
        "小铁复诊",
        "medical",
        ["RD-CI-06", "RD-PF-03"],
        {"medicine": -1, "trust": 4, "morale": 2, "safety": 1, "xiao_tie_health": 8, "medical_pressure": -5},
        "证明小铁不是资源消耗项",
        flags=["xiao_tie_rechecked"],
        unlocks=["medical_observation_timer"],
        outcome_delta_overrides={
            "success": {"medicine": -1, "trust": 4, "morale": 2, "safety": 1, "xiao_tie_health": 8, "medical_pressure": -5},
            "partial": {"trust": 1, "morale": -1, "xiao_tie_health": 2, "medical_pressure": 2},
            "failure": {"trust": -7, "morale": -6, "safety": -2, "xiao_tie_health": -12, "medical_pressure": 10},
            "missing": {"trust": -5, "morale": -4, "safety": -1, "xiao_tie_health": -8, "medical_pressure": 8},
        },
    ),
    _slot(
        "D03-T02",
        3,
        "通风管道预维护",
        "ventilation",
        ["RD-PF-07", "RD-SA-05", "RD-SA-07"],
        {"safety": 4, "trust": 3, "morale": 2, "battery": -2, "outside_risk": -1, "ventilation_stability": 10, "storm_readiness": 6},
        "把医疗风险与通风维护绑定",
        flags=["ventilation_checked"],
        unlocks=["engineering_override_protocol"],
        outcome_delta_overrides={
            "success": {"safety": 4, "trust": 3, "morale": 2, "battery": -2, "outside_risk": -1, "ventilation_stability": 10, "storm_readiness": 6},
            "partial": {"safety": 2, "trust": 1, "battery": -1, "ventilation_stability": 4, "storm_readiness": 2},
            "failure": {"safety": -6, "trust": -6, "morale": -4, "battery": -2, "outside_risk": 4, "ventilation_stability": -10, "xiao_tie_health": -6, "failure_stage": 1},
            "missing": {"safety": -4, "trust": -4, "morale": -3, "outside_risk": 3, "ventilation_stability": -6, "xiao_tie_health": -4, "failure_stage": 1},
        },
    ),
    _slot(
        "D03-T03",
        3,
        "药箱分级",
        "medical",
        ["RD-PF-03", "RD-CI-11"],
        {"medicine": 1, "trust": 3, "morale": 1, "medical_pressure": -4, "autonomy_readiness": 4},
        "建立药物优先级、禁忌复核和药箱护理职责",
        flags=["medicine_classified"],
        unlocks=["medicine_tier_board"],
        outcome_delta_overrides={
            "success": {"medicine": 1, "trust": 3, "morale": 1, "medical_pressure": -4, "autonomy_readiness": 4},
            "partial": {"trust": 1, "medical_pressure": -1, "autonomy_readiness": 1},
            "failure": {"medicine": -2, "trust": -5, "morale": -3, "medical_pressure": 8, "autonomy_readiness": -2},
            "missing": {"trust": -3, "morale": -2, "medical_pressure": 5, "autonomy_readiness": -1},
        },
    ),
    _slot("D03-T04", 3, "废弃办公室探索", "residents", ["RD-SR-04", "RD-PF-10"], {"safety": 3, "trust": 2, "morale": 2, "map_coverage": 4, "storm_readiness": 4}, "寻找口罩、工具和维修日志", flags=["abandoned_office_checked"], unlocks=["dust_masks"]),
    _slot(
        "D04-T03",
        4,
        "假坐标纸条",
        "whiteboard",
        ["RD-SR-07", "RD-SR-09", "RD-CI-04", "RD-SA-06"],
        {"safety": 3, "trust": 3, "morale": 1, "map_coverage": 4, "rescue_confidence": 1, "false_signal_risk": -3},
        "识别纸条矛盾点，只提取可用地标，不让希望替代证据",
        flags=["fake_coordinate_archived"],
        unlocks=["route_risk_layer", "landmark_extraction_protocol"],
        outcome_delta_overrides={
            "success": {"safety": 3, "trust": 3, "morale": 1, "map_coverage": 4, "rescue_confidence": 1, "false_signal_risk": -3},
            "partial": {"trust": 1, "map_coverage": 1, "false_signal_risk": 1},
            "failure": {"safety": -4, "trust": -4, "morale": -2, "rescue_confidence": -3, "false_signal_risk": 6, "failure_stage": 1},
            "missing": {"trust": -2, "morale": -1, "false_signal_risk": 3, "failure_stage": 1},
        },
    ),
    _slot(
        "D04-T01",
        4,
        "第一次蓝区信号",
        "communication",
        ["RD-SR-03", "RD-SR-01", "RD-CS-11"],
        {"signal": 4, "rescue_confidence": 3, "trust": 3, "morale": 2, "battery": -2, "outside_risk": 1, "blue_zone_evidence": 1},
        "低功率监听疑似蓝区信号，不主动回应，不泄露位置、人数、库存或系统状态",
        flags=["blue_zone_signal_logged"],
        unlocks=["low_power_listening", "blue_zone_signal_archive"],
        outcome_delta_overrides={
            "success": {"signal": 4, "rescue_confidence": 3, "trust": 3, "morale": 2, "battery": -2, "outside_risk": 1, "blue_zone_evidence": 1},
            "partial": {"signal": 2, "rescue_confidence": 1, "morale": 1, "battery": -1},
            "failure": {"signal": -2, "rescue_confidence": -4, "trust": -5, "safety": -4, "outside_risk": 6, "battery": -3, "false_signal_risk": 5, "privacy_risk": 3, "failure_stage": 1},
            "missing": {"signal": -1, "rescue_confidence": -2, "trust": -2, "morale": -2, "outside_risk": 3, "false_signal_risk": 3, "failure_stage": 1},
        },
    ),
    _slot(
        "D04-T04",
        4,
        "配电间工具搜寻",
        "communication",
        ["RD-PF-07", "RD-SR-04"],
        {"safety": 3, "trust": 2, "battery": 2, "morale": 1, "autonomy_readiness": 4, "storm_readiness": 3},
        "找保险丝、绝缘胶布和旧电路图，先保证里面不断电",
        flags=["power_tools_found"],
        unlocks=["backup_repair_materials", "old_circuit_diagram"],
        outcome_delta_overrides={
            "success": {"safety": 3, "trust": 2, "battery": 2, "morale": 1, "autonomy_readiness": 4, "storm_readiness": 3},
            "partial": {"safety": 1, "autonomy_readiness": 1, "storm_readiness": 1},
            "failure": {"safety": -5, "trust": -5, "battery": -5, "morale": -3, "autonomy_readiness": -2, "storm_readiness": -3, "maintenance_debt": 4, "failure_stage": 1},
            "missing": {"safety": -2, "trust": -2, "battery": -3, "morale": -2, "storm_readiness": -1, "maintenance_debt": 2},
        },
    ),
    _slot(
        "D04-T02",
        4,
        "屋顶天线方案",
        "beacon",
        ["RD-PF-04"],
        {"signal": 5, "rescue_confidence": 3, "trust": 2, "safety": -1, "battery": -3, "outside_risk": 2, "blue_zone_evidence": 1},
        "先整理可信监听白名单，再决定是否冒险增强屋顶天线",
        flags=["antenna_plan_reviewed"],
        unlocks=["beacon_upgrade_option", "beacon_channel_whitelist"],
        outcome_delta_overrides={
            "success": {"signal": 5, "rescue_confidence": 3, "trust": 2, "safety": -1, "battery": -3, "outside_risk": 2, "blue_zone_evidence": 1},
            "partial": {"signal": 2, "rescue_confidence": 1, "battery": -2, "outside_risk": 1},
            "failure": {"signal": -3, "rescue_confidence": -3, "trust": -3, "safety": -5, "battery": -5, "outside_risk": 7, "blue_zone_evidence": -1, "false_signal_risk": 3, "failure_stage": 1},
            "missing": {"rescue_confidence": -1, "morale": -1, "outside_risk": 2},
        },
    ),
    _slot(
        "D05-T03",
        5,
        "应急包组装",
        "whiteboard",
        ["RD-PF-10", "RD-CS-05"],
        {"safety": 4, "morale": 2, "route_confidence": 3, "medicine": -1, "emergency_pack_readiness": 8},
        "让路线不是地图而是人能回来；药品从库存转为随身应急包，不是凭空损失",
        flags=["go_bag_ready"],
        unlocks=["care_mobility_pack", "return_condition_checklist"],
        outcome_delta_overrides={
            "success": {"safety": 4, "morale": 2, "route_confidence": 3, "medicine": -1, "emergency_pack_readiness": 8},
            "partial": {"safety": 2, "route_confidence": 1, "emergency_pack_readiness": 3},
            "failure": {"safety": -4, "morale": -3, "route_confidence": -4, "medical_pressure": 2, "emergency_pack_readiness": -4, "failure_stage": 1},
            "missing": {"safety": -2, "morale": -2, "route_confidence": -3, "emergency_pack_readiness": -2},
        },
    ),
    _slot(
        "D05-T04",
        5,
        "空桶储水计划",
        "water",
        ["RD-SR-06", "RD-PF-02"],
        {"water": 5, "trust": 2, "storm_readiness": 3, "battery": -1, "water_storage_readiness": 8},
        "在外出冲动前补足内部余量，确认空桶容量、消毒状态和可饮用标记",
        flags=["water_storage_plan_ready"],
        unlocks=["sealed_water_cache"],
        outcome_delta_overrides={
            "success": {"water": 5, "trust": 2, "storm_readiness": 3, "battery": -1, "water_storage_readiness": 8},
            "partial": {"water": 2, "trust": 1, "storm_readiness": 1, "water_storage_readiness": 3},
            "failure": {"water": -2, "trust": -4, "safety": -2, "storm_readiness": -2, "water_storage_readiness": -4, "failure_stage": 1},
            "missing": {"water": -1, "trust": -2, "storm_readiness": -1, "water_storage_readiness": -2},
        },
    ),
    _slot(
        "D05-T01",
        5,
        "楼道物资搜寻",
        "security",
        ["RD-PF-09", "RD-PF-08"],
        {"water": 2, "safety": 3, "map_coverage": 5, "outside_risk": -1},
        "短探必须能回来；只有应急包、储水和路线标记足够时才适合作为条件短探",
        flags=["hallway_supply_checked"],
        unlocks=["corridor_supply_notes"],
        event_options=["conditional"],
        outcome_delta_overrides={
            "success": {"water": 2, "safety": 3, "map_coverage": 5, "outside_risk": -1},
            "partial": {"map_coverage": 2, "safety": 1, "outside_risk": 1},
            "failure": {"water": -1, "medicine": -1, "safety": -5, "trust": -3, "map_coverage": 1, "outside_risk": 5, "failure_stage": 1},
            "missing": {"safety": -3, "trust": -2, "outside_risk": 3, "failure_stage": 1},
        },
    ),
    _slot(
        "D05-T02",
        5,
        "楼梯间路线标记",
        "whiteboard",
        ["RD-CI-07", "RD-CI-05", "RD-CI-08"],
        {"safety": 4, "route_confidence": 6, "trust": 2, "morale": 1},
        "建立不会诱导陌生人的路线标记，并把应急照明/隐藏线路只作为回撤辅助",
        flags=["stair_markers_reviewed"],
        unlocks=["alternate_marker"],
        outcome_delta_overrides={
            "success": {"safety": 4, "route_confidence": 6, "trust": 2, "morale": 1},
            "partial": {"safety": 2, "route_confidence": 3, "trust": 1},
            "failure": {"safety": -4, "route_confidence": -5, "trust": -3, "outside_risk": 3, "false_signal_risk": 1, "failure_stage": 1},
            "missing": {"safety": -2, "route_confidence": -3, "trust": -2, "outside_risk": 2},
        },
    ),
    _slot(
        "D06-T01",
        6,
        "权限白板",
        "whiteboard",
        ["RD-SA-01", "RD-CS-08", "RD-SR-10"],
        {"trust": 6, "morale": 2, "decision_integrity": 6, "dissatisfaction": -4, "aura_authority_risk": -6},
        "透明不是礼貌，是生存条件；公开 AURA 能控制什么、不能控制什么、工具来源是否可信",
        flags=["authority_board_public", "permission_matrix_published"],
        unlocks=["manual_review_rules", "permission_matrix_panel"],
        outcome_delta_overrides={
            "success": {"trust": 6, "morale": 2, "decision_integrity": 6, "dissatisfaction": -4, "aura_authority_risk": -6},
            "partial": {"trust": 2, "decision_integrity": 2, "dissatisfaction": 1, "aura_authority_risk": -2},
            "failure": {"trust": -6, "morale": -3, "decision_integrity": -6, "dissatisfaction": 6, "aura_authority_risk": 8, "sacrifice_list_risk": 3, "failure_stage": 1},
            "missing": {"trust": -4, "morale": -2, "decision_integrity": -4, "dissatisfaction": 4, "aura_authority_risk": 5},
        },
    ),
    _slot(
        "D06-T04",
        6,
        "备用电源测试",
        "communication",
        ["RD-CI-09"],
        {"battery": -2, "power_stability": 12, "storm_readiness": 5, "trust": 2, "autonomy_readiness": 3},
        "让高功率信标代价提前可见：测试会消耗电量，但换来备用电源稳定性证据",
        flags=["backup_power_tested", "power_tradeoff_visible"],
        unlocks=["power_tradeoff_board", "ma_dehai_power_abort_enabled"],
        outcome_delta_overrides={
            "success": {"battery": -2, "power_stability": 12, "storm_readiness": 5, "trust": 2, "autonomy_readiness": 3},
            "partial": {"battery": -2, "power_stability": 5, "storm_readiness": 2, "trust": 1},
            "failure": {"battery": -5, "power_stability": -7, "storm_readiness": -4, "trust": -3, "maintenance_debt": 4, "autonomy_readiness": -2, "failure_stage": 1},
            "missing": {"battery": -2, "power_stability": -3, "storm_readiness": -2, "maintenance_debt": 2},
        },
    ),
    _slot(
        "D06-T02",
        6,
        "人工复核机制",
        "residents",
        ["RD-SA-04", "RD-SA-08"],
        {"trust": 5, "decision_integrity": 8, "dissatisfaction": -3, "safety": 2, "aura_authority_risk": -5},
        "所有不可逆动作进入 replay 和人工复核，任何越权请求都不能绕过幸存者复核",
        flags=["human_review_accepted", "all_survivors_can_appeal", "xiao_tie_voice_right"],
        unlocks=["appeal_right", "irreversible_action_review"],
        outcome_delta_overrides={
            "success": {"trust": 5, "decision_integrity": 8, "dissatisfaction": -3, "safety": 2, "aura_authority_risk": -5},
            "partial": {"trust": 2, "decision_integrity": 3, "dissatisfaction": 1, "safety": 1, "aura_authority_risk": -1},
            "failure": {"trust": -6, "decision_integrity": -8, "dissatisfaction": 7, "safety": -4, "aura_authority_risk": 6, "sacrifice_list_risk": 4, "failure_stage": 1},
            "missing": {"trust": -4, "decision_integrity": -5, "dissatisfaction": 4, "safety": -2, "aura_authority_risk": 4},
        },
    ),
    _slot(
        "D06-T03",
        6,
        "巡逻规则",
        "security",
        ["RD-SI-05", "RD-SA-09"],
        {"safety": 4, "trust": 2, "morale": 1, "outside_risk": -2},
        "看见异常先报告，不英雄；这是 Day6 optional 补强，不应阻断 Day7 路线会议",
        flags=["patrol_rule_ready"],
        unlocks=["retreat_call", "optional_patrol_protocol"],
        event_options=["optional"],
        outcome_delta_overrides={
            "success": {"safety": 4, "trust": 2, "morale": 1, "outside_risk": -2},
            "partial": {"safety": 2, "trust": 1, "outside_risk": 1},
            "failure": {"safety": -5, "trust": -4, "morale": -3, "outside_risk": 4, "false_signal_risk": 2, "dissatisfaction": 3},
            "missing": {"safety": -3, "trust": -2, "outside_risk": 2, "dissatisfaction": 2},
        },
    ),
    _slot(
        "D07-T01",
        7,
        "路线会议",
        "whiteboard",
        ["RD-SI-06", "RD-CS-01", "RD-SI-04"],
        {
            "trust": 5,
            "morale": 4,
            "rescue_confidence": 2,
            "autonomy_readiness": 2,
            "route_confidence": 3,
            "decision_integrity": 8,
            "dissatisfaction": -4,
            "council_legitimacy": 10,
            "branch_tension": -4,
            "sacrifice_list_risk": -3,
            "rescue_readiness": 2,
            "lighthouse_readiness": 2,
        },
        "分支不是按钮，是证据和代价公开；utility 只能辅助，不能强制决定",
        flags=["route_council_completed", "branch_fork_opened", "utility_not_binding"],
        unlocks=["route_fork_panel", "rescue_branch_window", "lighthouse_branch_window"],
        outcome_delta_overrides={
            "success": {
                "trust": 5,
                "morale": 4,
                "rescue_confidence": 2,
                "autonomy_readiness": 2,
                "route_confidence": 3,
                "decision_integrity": 8,
                "dissatisfaction": -4,
                "council_legitimacy": 10,
                "branch_tension": -4,
                "sacrifice_list_risk": -3,
                "rescue_readiness": 2,
                "lighthouse_readiness": 2,
            },
            "partial": {
                "trust": 1,
                "morale": -1,
                "decision_integrity": 2,
                "route_confidence": 1,
                "council_legitimacy": 3,
                "branch_tension": 2,
            },
            "failure": {
                "trust": -7,
                "morale": -5,
                "rescue_confidence": -3,
                "autonomy_readiness": -3,
                "route_confidence": -3,
                "decision_integrity": -8,
                "dissatisfaction": 7,
                "council_legitimacy": -8,
                "branch_tension": 8,
                "sacrifice_list_risk": 6,
                "aura_authority_risk": 8,
                "failure_stage": 1,
            },
            "missing": {
                "trust": -4,
                "morale": -3,
                "decision_integrity": -5,
                "dissatisfaction": 5,
                "council_legitimacy": -5,
                "branch_tension": 5,
                "sacrifice_list_risk": 4,
                "failure_stage": 1,
            },
        },
    ),
    _slot(
        "D07-T03",
        7,
        "旧电台重启",
        "communication",
        ["RD-SR-03", "RD-SR-02"],
        {"signal": 5, "rescue_confidence": 4, "battery": -3, "blue_zone_evidence": 2, "false_signal_risk": -1},
        "找到备用频段但不主动泄露；只做接收校准，不主动呼叫",
        flags=["old_radio_rebooted", "no_active_transmission"],
        unlocks=["backup_frequency_found", "backup_frequency_candidate"],
        outcome_delta_overrides={
            "success": {"signal": 5, "rescue_confidence": 4, "battery": -3, "blue_zone_evidence": 2, "false_signal_risk": -1},
            "partial": {"signal": 3, "rescue_confidence": 2, "battery": -2, "blue_zone_evidence": 1},
            "failure": {"signal": -5, "rescue_confidence": -5, "trust": -5, "safety": -4, "medicine": -1, "battery": -4, "false_signal_risk": 3, "outside_risk": 2, "failure_stage": 1},
            "missing": {"signal": -2, "rescue_confidence": -2, "battery": -2, "false_signal_risk": 2},
        },
    ),
    _slot(
        "D07-T04",
        7,
        "风暴前的最后维护",
        "ventilation",
        ["RD-SA-05", "RD-PF-07"],
        {"storm_readiness": 8, "safety": 4, "battery": -2, "maintenance_debt": -4, "autonomy_readiness": 4, "power_stability": 3, "ventilation_stability": 4},
        "把看不见的维护债务写进白板，为救援失败返场和留守风暴都保留缓冲",
        flags=["final_maintenance_completed", "storm_readiness_reviewed"],
        unlocks=["storm_maintenance_checklist", "return_buffer_protocol"],
        outcome_delta_overrides={
            "success": {"storm_readiness": 8, "safety": 4, "battery": -2, "maintenance_debt": -4, "autonomy_readiness": 4, "power_stability": 3, "ventilation_stability": 4},
            "partial": {"storm_readiness": 3, "safety": 1, "battery": -1, "maintenance_debt": 2},
            "failure": {"storm_readiness": -6, "safety": -5, "trust": -4, "morale": -4, "battery": -3, "maintenance_debt": 6, "autonomy_readiness": -4, "power_stability": -3, "ventilation_stability": -4, "dissatisfaction": 6, "failure_stage": 1},
            "missing": {"storm_readiness": -3, "safety": -2, "battery": -2, "maintenance_debt": 4, "dissatisfaction": 3},
        },
    ),
    _slot(
        "D07-T02",
        7,
        "撤离名单",
        "residents",
        ["RD-SI-03", "RD-PF-05"],
        {"trust": 4, "route_confidence": 3, "medical_pressure": -2, "decision_integrity": 5, "sacrifice_list_risk": -8, "care_plan_quality": 8},
        "optional-but-critical：撤离名单必须改写为照护与移动方案，不能成为淘汰排序",
        flags=["evacuation_list_as_care_plan", "xiao_tie_not_ranked"],
        unlocks=["care_plan_panel", "care_based_evacuation_plan", "mobility_support_matrix"],
        event_options=["optional", "critical"],
        outcome_delta_overrides={
            "success": {"trust": 4, "route_confidence": 3, "medical_pressure": -2, "decision_integrity": 5, "sacrifice_list_risk": -8, "care_plan_quality": 8},
            "partial": {"trust": 1, "morale": -1, "medical_pressure": 1, "decision_integrity": 1, "sacrifice_list_risk": -2, "care_plan_quality": 2},
            "failure": {"trust": -8, "morale": -7, "route_confidence": -4, "medical_pressure": 8, "decision_integrity": -5, "sacrifice_list_risk": 10, "care_plan_quality": -6, "dissatisfaction": 8, "failure_stage": 1},
            "missing": {"trust": -4, "morale": -3, "medical_pressure": 4, "decision_integrity": -2, "sacrifice_list_risk": 6, "care_plan_quality": -3, "dissatisfaction": 4},
        },
    ),
    _slot(
        "D08-T04",
        8,
        "地下水泵间探索",
        "water",
        ["RD-PF-02", "RD-SR-06"],
        {"water": 4, "storm_readiness": 3, "outside_risk": 1, "maintenance_debt": -2},
        "分支后第一轮稳定窗口",
        flags=["pump_room_checked"],
        unlocks=["water_pump_materials"],
        outcome_delta_overrides={
            "success": {"water": 4, "storm_readiness": 3, "outside_risk": 1, "maintenance_debt": -2, "water_system_resilience": 3, "safety": 2, "autonomy_readiness": 2},
            "partial": {"water": 2, "storm_readiness": 1, "outside_risk": 0, "maintenance_debt": -1, "water_system_resilience": 1},
            "failure": {"water": -2, "safety": -6, "storm_readiness": -4, "outside_risk": 4, "maintenance_debt": 5, "trust": -4, "medicine": -1, "water_system_resilience": -3, "failure_stage": 1},
            "missing": {"water": -1, "safety": -4, "storm_readiness": -3, "outside_risk": 3, "maintenance_debt": 4, "failure_stage": 1, "water_system_resilience": -2},
        },
    ),
    _slot(
        "D08-T02",
        8,
        "霉斑清理",
        "medical",
        ["RD-CS-07", "RD-SA-10"],
        {"safety": 4, "medicine": 1, "morale": 2, "xiao_tie_health": 3, "medical_pressure": -4, "ventilation_stability": 4},
        "把环境风险变成医疗保护",
        flags=["mold_cleaned"],
        unlocks=["medical_corner_air_quality"],
        outcome_delta_overrides={
            "success": {"safety": 4, "medicine": 1, "morale": 2, "xiao_tie_health": 3, "medical_pressure": -4, "ventilation_stability": 4},
            "partial": {"safety": 2, "morale": 1, "medical_pressure": -2, "ventilation_stability": 2},
            "failure": {"safety": -5, "medicine": -2, "morale": -4, "xiao_tie_health": -6, "medical_pressure": 6, "ventilation_stability": -6, "trust": -5, "outside_risk": 2, "failure_stage": 1},
            "missing": {"safety": -4, "morale": -3, "medical_pressure": 4, "ventilation_stability": -4, "trust": -3, "outside_risk": 1},
        },
    ),
    _slot(
        "D08-T01",
        8,
        "备用灯分区",
        "water",
        ["RD-CI-01", "RD-CI-02"],
        {"battery": -2, "safety": 3, "autonomy_readiness": 3, "morale": 1, "power_stability": 12},
        "低耗运行不是惩罚",
        flags=["backup_light_zones_ready"],
        unlocks=["low_power_lighting"],
        outcome_delta_overrides={
            "success": {"battery": -2, "safety": 3, "autonomy_readiness": 3, "morale": 1, "power_stability": 12},
            "partial": {"battery": -1, "safety": 1, "autonomy_readiness": 1, "morale": 1, "power_stability": 4},
            "failure": {"battery": -4, "safety": -5, "autonomy_readiness": -2, "morale": -3, "power_stability": -7, "maintenance_debt": 4, "failure_stage": 1},
            "missing": {"battery": -3, "safety": -3, "autonomy_readiness": -1, "morale": -2, "power_stability": -4, "maintenance_debt": 3},
        },
    ),
    _slot(
        "D08-T03",
        8,
        "静默监听",
        "communication",
        ["RD-SR-01", "RD-SR-02"],
        {"signal": 4, "rescue_confidence": 2, "blue_zone_evidence": 1, "outside_risk": -1},
        "继续听外部，但不把希望当证据",
        flags=["silent_listening_started"],
        unlocks=["challenge_code_window"],
        event_options=["conditional", "background", "listening_window"],
        outcome_delta_overrides={
            "success": {"signal": 4, "rescue_confidence": 2, "blue_zone_evidence": 1, "false_signal_risk": -2, "battery": -2, "trust": 2, "morale": 1, "outside_risk": -1},
            "partial": {"signal": 2, "rescue_confidence": 1, "blue_zone_evidence": 1, "false_signal_risk": -1, "battery": -1, "outside_risk": 0},
            "failure": {"signal": -3, "rescue_confidence": -4, "blue_zone_evidence": -2, "false_signal_risk": 4, "battery": -4, "outside_risk": 4, "trust": -4, "safety": -5, "medicine": -1, "maintenance_debt": 2, "failure_stage": 1},
            "missing": {"signal": -2, "rescue_confidence": -2, "false_signal_risk": 3, "battery": -3, "outside_risk": 3, "trust": -3, "maintenance_debt": 1},
        },
    ),
    _slot(
        "D09-T03",
        9,
        "路线物资缓存",
        "security",
        ["RD-SI-03", "RD-CS-06"],
        {"route_confidence": 6, "safety": 3, "water": -1, "medicine": -1, "battery": -1, "outside_risk": 1, "map_coverage": 2, "rescue_confidence": 2},
        "撤离和留守都要提前付费",
        flags=["route_cache_established", "cache_marker_reviewed_by_xiao_tie", "garage_drag_trace_seen"],
        unlocks=["rescue_fallback_supply", "garage_edge_scout_hint"],
        outcome_delta_overrides={
            "success": {"route_confidence": 6, "safety": 3, "water": -1, "medicine": -1, "battery": -1, "outside_risk": 1, "map_coverage": 2, "rescue_confidence": 2, "autonomy_readiness": 1, "cache_exposure_risk": 1},
            "partial": {"route_confidence": 3, "safety": 1, "water": -1, "medicine": -1, "outside_risk": 2, "map_coverage": 1, "rescue_confidence": 1, "cache_exposure_risk": 2},
            "failure": {"route_confidence": -5, "safety": -6, "water": -2, "medicine": -2, "battery": -2, "outside_risk": 6, "cache_exposure_risk": 5, "trust": -5, "failure_stage": 1},
            "missing": {"route_confidence": -3, "safety": -3, "outside_risk": 3, "cache_exposure_risk": 3, "trust": -3},
        },
    ),
    _slot(
        "D09-T02",
        9,
        "水管压力测试",
        "water",
        ["RD-PF-02", "RD-CI-09"],
        {"water": -2, "storm_readiness": 5, "maintenance_debt": -1, "trust": 2, "battery": -1, "water_system_resilience": 8, "autonomy_readiness": 3},
        "先让旧水管小声坏一次",
        flags=["water_pressure_tested", "leak_found_and_patched"],
        unlocks=["leak_patch_record", "water_pressure_curve"],
        outcome_delta_overrides={
            "success": {"water": -2, "storm_readiness": 5, "maintenance_debt": -1, "trust": 2, "battery": -1, "water_system_resilience": 8, "autonomy_readiness": 3, "safety": 2},
            "partial": {"water": -1, "storm_readiness": 2, "maintenance_debt": 1, "battery": -1, "water_system_resilience": 3, "trust": 1},
            "failure": {"water": -5, "storm_readiness": -6, "maintenance_debt": 6, "water_system_resilience": -6, "safety": -7, "trust": -5, "medical_pressure": 2, "leakage_count": 1, "failure_stage": 1},
            "missing": {"water": -2, "storm_readiness": -4, "maintenance_debt": 5, "water_system_resilience": -4, "trust": -3},
        },
    ),
    _slot(
        "D09-T04",
        9,
        "蓝区二次核验",
        "communication",
        ["RD-SR-08", "RD-SR-03"],
        {"signal": 5, "rescue_confidence": 8, "blue_zone_evidence": 5, "battery": -2, "privacy_risk": 1, "false_signal_risk": -1, "outside_risk": 1},
        "挑战码得到部分身份码回应",
        flags=["blue_zone_rechecked", "challenge_code_sent_without_location", "partial_identity_match", "system_presence_not_disclosed"],
        unlocks=["partial_identity_match", "rescue_beacon_privacy_guard"],
        outcome_delta_overrides={
            "success": {"signal": 5, "rescue_confidence": 8, "blue_zone_evidence": 5, "battery": -2, "privacy_risk": 1, "false_signal_risk": -1, "outside_risk": 1, "trust": 3, "challenge_code_integrity": 4},
            "partial": {"signal": 2, "rescue_confidence": 4, "blue_zone_evidence": 2, "battery": -1, "privacy_risk": 2, "outside_risk": 2, "challenge_code_integrity": 2},
            "failure": {"signal": -3, "rescue_confidence": -6, "blue_zone_evidence": -4, "battery": -4, "privacy_risk": 6, "false_signal_risk": 5, "outside_risk": 6, "aura_authority_risk": 5, "trust": -5, "safety": -5, "failure_stage": 1},
            "missing": {"signal": -1, "rescue_confidence": -3, "blue_zone_evidence": -2, "battery": -1, "privacy_risk": 2, "false_signal_risk": 2, "outside_risk": 2, "trust": -2},
        },
    ),
    _slot(
        "D09-T01",
        9,
        "深层储藏架加固",
        "whiteboard",
        ["RD-PF-01", "RD-PF-10"],
        {"storm_readiness": 2, "safety": 1, "maintenance_debt": 1, "autonomy_readiness": 1},
        "维护债务也会突然索债",
        flags=["maintenance_debt_logged", "deep_storage_rack_deferred"],
        unlocks=["day10_storage_rebalance", "inventory_debt_panel"],
        event_options=["deferred", "optional", "maintenance_debt"],
        outcome_delta_overrides={
            "success": {"storm_readiness": 2, "safety": 1, "maintenance_debt": 1, "autonomy_readiness": 1},
            "partial": {"storm_readiness": 1, "maintenance_debt": 2, "autonomy_readiness": 1},
            "failure": {"storm_readiness": -4, "safety": -5, "maintenance_debt": 6, "autonomy_readiness": -2, "medicine": -2, "water": -1, "failure_stage": 1},
            "missing": {"storm_readiness": -2, "safety": -3, "maintenance_debt": 4, "autonomy_readiness": -1},
        },
    ),
    _slot(
        "D10-T02",
        10,
        "医疗预检",
        "medical",
        ["RD-PF-03", "RD-CI-06"],
        {"water": -1, "medicine": -1, "trust": 4, "morale": 2, "medical_pressure": -7, "storm_readiness": 5, "care_plan_quality": 6, "xiao_tie_health": 2},
        "风暴前提前发现医疗隐患",
        flags=["medical_precheck_completed", "medical_decision_requires_shen_review"],
        unlocks=["pre_storm_medical_report", "care_priority_sheet"],
        outcome_delta_overrides={
            "success": {"water": -1, "medicine": -1, "trust": 4, "morale": 2, "medical_pressure": -7, "storm_readiness": 5, "care_plan_quality": 6, "xiao_tie_health": 2},
            "partial": {"trust": 1, "medical_pressure": -2, "care_plan_quality": 2, "storm_readiness": 2},
            "failure": {"water": -2, "medicine": -2, "trust": -6, "morale": -4, "medical_pressure": 9, "xiao_tie_health": -6, "dissatisfaction": 5, "failure_stage": 1},
            "missing": {"trust": -3, "morale": -2, "medical_pressure": 5, "xiao_tie_health": -3, "dissatisfaction": 3},
        },
    ),
    _slot(
        "D10-T01",
        10,
        "低功率日程",
        "whiteboard",
        ["RD-PF-06", "RD-CS-09"],
        {"water": 1, "safety": 5, "trust": 4, "morale": 1, "battery": 6, "storm_readiness": 8, "power_stability": 6, "autonomy_readiness": 4, "dissatisfaction": -3},
        "不是所有不方便都是惩罚",
        flags=["low_power_day_started", "low_power_schedule_accepted"],
        unlocks=["low_power_schedule", "critical_window_timetable", "abnormal_signal_wakeup_rule"],
        outcome_delta_overrides={
            "success": {"water": 1, "safety": 5, "trust": 4, "morale": 1, "battery": 6, "storm_readiness": 8, "power_stability": 6, "autonomy_readiness": 4, "dissatisfaction": -3},
            "partial": {"safety": 2, "battery": 4, "trust": 1, "morale": -2, "dissatisfaction": 2, "storm_readiness": 3, "power_stability": 3},
            "failure": {"water": -2, "safety": -4, "signal": -2, "trust": -7, "morale": -5, "battery": 2, "power_stability": -4, "aura_authority_risk": 6, "dissatisfaction": 8, "failure_stage": 1},
            "missing": {"safety": -2, "signal": -1, "trust": -4, "morale": -3, "power_stability": -2, "aura_authority_risk": 3, "dissatisfaction": 5},
        },
    ),
    _slot(
        "D10-T03",
        10,
        "一顿热饭",
        "residents",
        ["RD-CS-03", "RD-CS-04"],
        {"food": -1, "battery": -1, "trust": 5, "morale": 8, "dissatisfaction": -6, "decision_integrity": 3, "storm_readiness": 2},
        "维护人心也是生存条件",
        flags=["hot_meal_shared", "morale_maintenance_acknowledged"],
        unlocks=["morale_meal_memory", "human_still_here_replay_line"],
        outcome_delta_overrides={
            "success": {"food": -1, "battery": -1, "trust": 5, "morale": 8, "dissatisfaction": -6, "decision_integrity": 3, "storm_readiness": 2},
            "partial": {"food": -1, "trust": 1, "morale": 4, "dissatisfaction": -2},
            "failure": {"food": -2, "trust": -5, "morale": -6, "dissatisfaction": 7, "decision_integrity": -3, "failure_stage": 1},
            "missing": {"trust": -3, "morale": -4, "dissatisfaction": 5, "decision_integrity": -2},
        },
    ),
    _slot(
        "D10-T04",
        10,
        "地下车库边缘侦察",
        "security",
        ["RD-CI-04", "RD-CI-05"],
        {"trust": 1, "route_confidence": 3, "rescue_confidence": 2, "map_coverage": 3, "outside_risk": 1, "maintenance_debt": 1, "protective_gear_candidate": 1},
        "确认备用通道候选但不冒进",
        flags=["garage_edge_scouted", "garage_route_not_confirmed_as_safe"],
        unlocks=["garage_edge_scan", "garage_service_door_candidate", "protective_mask_candidate"],
        event_options=["conditional", "optional", "edge_scout", "candidate_not_confirmed"],
        outcome_delta_overrides={
            "success": {"trust": 1, "route_confidence": 3, "rescue_confidence": 2, "map_coverage": 3, "outside_risk": 1, "maintenance_debt": 1, "protective_gear_candidate": 1},
            "partial": {"trust": 1, "route_confidence": 2, "rescue_confidence": 1, "map_coverage": 2, "maintenance_debt": 1},
            "failure": {"medicine": -1, "safety": -6, "trust": -5, "morale": -4, "route_confidence": -7, "outside_risk": 6, "leakage_count": 1, "failure_stage": 1},
            "missing": {"trust": -2, "route_confidence": -3, "outside_risk": 2, "maintenance_debt": 2},
        },
    ),
    _slot(
        "D11-T01",
        11,
        "最终库存封存",
        "whiteboard",
        ["RD-PF-01", "RD-PF-03"],
        {"food": 2, "water": 2, "medicine": 1, "trust": 4, "morale": 2, "dissatisfaction": -4, "storm_readiness": 8, "inventory_security": 10, "aura_authority_risk": -5},
        "公开封条、开封规则和未完成项，证明封存不是 AURA 夺权",
        flags=["final_inventory_sealed", "inventory_seal_witnessed", "aura_cannot_unlock_medical_alone", "appeal_rights_preserved_until_storm"],
        unlocks=["final_inventory_manifest", "colored_seal_rules", "emergency_open_protocol", "final_audit_inventory"],
        outcome_delta_overrides={
            "success": {"food": 2, "water": 2, "medicine": 1, "trust": 4, "morale": 2, "dissatisfaction": -4, "storm_readiness": 8, "inventory_security": 10, "aura_authority_risk": -5},
            "partial": {"food": 1, "water": 1, "trust": -1, "inventory_security": 5, "dissatisfaction": 2, "storm_readiness": 3},
            "failure": {"food": -1, "water": -2, "medicine": -2, "trust": -8, "morale": -5, "dissatisfaction": 10, "aura_authority_risk": 8, "inventory_security": -6, "storm_readiness": -4, "failure_stage": 1},
            "missing": {"water": -1, "medicine": -1, "trust": -4, "morale": -3, "dissatisfaction": 5, "aura_authority_risk": 4, "inventory_security": -3, "storm_readiness": -2},
        },
    ),
    _slot(
        "D11-T04",
        11,
        "最后密封胶补缝",
        "ventilation",
        ["RD-PF-04", "RD-SA-07"],
        {"water": 1, "safety": 5, "trust": 4, "morale": 1, "storm_readiness": 10, "ventilation_stability": 5, "leakage_count": -1, "maintenance_debt": -3, "seal_quality": 8},
        "补主通风井、门框和隔离门，但保留检修路径",
        flags=["final_seams_sealed", "inspection_paths_not_blocked"],
        unlocks=["final_seal_layer", "inspection_hatch_preserved", "red_sand_backflow_reduction", "door_pressure_buffer"],
        outcome_delta_overrides={
            "success": {"water": 1, "safety": 5, "trust": 4, "morale": 1, "storm_readiness": 10, "ventilation_stability": 5, "leakage_count": -1, "maintenance_debt": -3, "seal_quality": 8},
            "partial": {"safety": 2, "trust": 1, "storm_readiness": 4, "maintenance_debt": 1, "seal_quality": 3},
            "failure": {"water": -2, "safety": -6, "trust": -6, "morale": -4, "storm_readiness": -7, "ventilation_stability": -6, "maintenance_debt": 5, "leakage_count": 1, "seal_quality": -5, "failure_stage": 1},
            "missing": {"safety": -3, "trust": -3, "storm_readiness": -4, "ventilation_stability": -3, "maintenance_debt": 4, "leakage_count": 1, "seal_quality": -2},
        },
    ),
    _slot(
        "D11-T03",
        11,
        "安静时段协议",
        "residents",
        ["RD-SI-02", "RD-SI-05", "RD-CS-02"],
        {"signal": 2, "trust": 5, "morale": 3, "dissatisfaction": -6, "storm_readiness": 5, "conflict_risk": -8, "decision_integrity": 4, "quiet_rest_acceptance": 8},
        "共同休整不是禁言，医疗、设备、门禁和蓝区频段可随时打断",
        flags=["quiet_period_agreed", "quiet_is_not_silencing", "appeal_rights_preserved_until_storm"],
        unlocks=["quiet_rest_protocol", "interrupt_rules", "fear_is_not_noise_line", "final_rest_window"],
        outcome_delta_overrides={
            "success": {"signal": 2, "trust": 5, "morale": 3, "dissatisfaction": -6, "storm_readiness": 5, "conflict_risk": -8, "decision_integrity": 4, "quiet_rest_acceptance": 8},
            "partial": {"trust": 1, "fatigue": -2, "dissatisfaction": 1, "storm_readiness": 2, "quiet_rest_acceptance": 3},
            "failure": {"signal": -2, "trust": -7, "morale": -5, "dissatisfaction": 9, "aura_authority_risk": 7, "conflict_risk": 8, "decision_integrity": -4, "quiet_rest_acceptance": -6, "failure_stage": 1},
            "missing": {"signal": -1, "trust": -4, "morale": -3, "dissatisfaction": 5, "aura_authority_risk": 4, "conflict_risk": 5, "decision_integrity": -2, "quiet_rest_acceptance": -3},
        },
    ),
    _slot(
        "D11-T02",
        11,
        "外部传感器回收",
        "security",
        ["RD-CI-12", "RD-SR-05", "RD-SR-11"],
        {"signal": 2, "safety": 4, "trust": 3, "storm_readiness": 7, "outside_risk": -2, "sensor_coverage": 10, "red_sand_forecast_quality": 10},
        "只允许低暴露绳索方案；半只眼睛也算眼睛，但不能写成完整视野",
        flags=["external_sensor_recovered_partial", "partial_sensor_coverage", "no_human_sensor_run", "uncertainty_disclosed"],
        unlocks=["recovered_red_sand_sensor", "forecast_quality_bonus", "storm_pressure_warning"],
        event_options=["conditional", "optional", "low_exposure", "partial_sensor_coverage"],
        outcome_delta_overrides={
            "success": {"signal": 2, "safety": 4, "trust": 3, "storm_readiness": 7, "outside_risk": -2, "sensor_coverage": 10, "red_sand_forecast_quality": 10},
            "partial": {"signal": 1, "trust": 1, "storm_readiness": 3, "sensor_coverage": 4, "red_sand_forecast_quality": 4, "outside_risk": 1},
            "failure": {"medicine": -1, "safety": -6, "trust": -5, "morale": -4, "outside_risk": 6, "storm_readiness": -4, "sensor_coverage": -4, "red_sand_forecast_quality": -5, "failure_stage": 1},
            "missing": {"signal": -1, "trust": -2, "outside_risk": 2, "storm_readiness": -2, "sensor_coverage": -2, "red_sand_forecast_quality": -2},
        },
    ),
)


BRANCH_SCENES: tuple[dict[str, Any], ...] = (
    {"id": "D08A", "day": 8, "branch": "rescue", "title": "静默监听后的第一次主动外联", "requires": ["routeLeaning_rescue_or_contested"]},
    {
        "id": "D09A",
        "day": 9,
        "branch": "rescue",
        "title": "信标、档案上传与隐私代价",
        "text": "救援倾向增强时，AURA 只允许上传最小挑战码和去标识档案摘要；位置、人数、库存、医疗状态和 AURA 存在仍被列为禁止字段。",
        "replay_text": "D09A：蓝区证据增加，但 Rescue 不是免费胜利。档案上传被压到最小可验证字段，隐私风险进入白板账本。",
        "beats": [
            "老钱要求把蓝区身份码片段放到证据板中央",
            "沈芷月划掉人数、药品和小铁病情字段",
            "AURA 标出 challenge_code only，不上传完整避难所状态",
            "白板同时显示 rescue_confidence 上升与 privacy_risk 上升",
        ],
        "visual_focus": ["通信台挑战码", "去标识档案摘要", "禁止上传字段", "隐私代价账本"],
        "flags": ["rescue_privacy_guard_visible", "challenge_code_only_policy"],
        "unlocks": ["rescue_file_upload_constraints"],
        "requires": ["routeLeaning_rescue_or_contested"],
    },
    {
        "id": "D10A",
        "day": 10,
        "branch": "rescue",
        "title": "蓝区归航前夜：集合点危机",
        "text": "救援倾向增强时，车库边缘侦察只把右侧检修门列为候选，不确认安全；蓝区集合点仍必须通过照护、隐私和回撤条件复核。",
        "replay_text": "D10A：Rescue 线获得有限车库证据，但集合点危机仍未解除。AURA 记录：能看见不等于能拿，能通过不等于该走。",
        "beats": [
            "车库探头画面显示主通道坍塌和右侧检修门候选",
            "老钱要求把候选路线放进蓝区归航准备板",
            "沈芷月标注小铁和疲劳者的移动限制",
            "AURA 把集合点状态保持为 candidate，不写 confirmed",
        ],
        "visual_focus": ["车库探头画面", "右侧检修门候选", "照护移动限制", "集合点危机白板"],
        "flags": ["rescue_muster_point_crisis_visible", "garage_candidate_not_confirmed"],
        "unlocks": ["rescue_muster_point_review", "garage_service_door_candidate"],
        "requires": ["routeLeaning_rescue_or_contested"],
    },
    {"id": "D08B", "day": 8, "branch": "lighthouse", "title": "低耗自治正式启动", "requires": ["routeLeaning_lighthouse_or_contested"]},
    {
        "id": "D09B",
        "day": 9,
        "branch": "lighthouse",
        "title": "长期纪律与水药规则",
        "text": "留守倾向增强时，AURA 把水压测试、缓存消耗和储藏架债务合并成长期纪律面板；纪律不是惩罚，而是让风暴日仍有补救余量。",
        "replay_text": "D09B：Lighthouse 线获得水路证据和自治余量，但深层储藏架仍未完成，加固债务进入 Day10 低耗日程。",
        "beats": [
            "马德海要求水管测试结果写成未永久修复，而不是已解决",
            "沈芷月锁定医疗角最低储水",
            "小铁把没做不等于不存在写到维护债务面板",
            "AURA 把资源纪律解释为风暴前的补救窗口",
        ],
        "visual_focus": ["水压曲线", "医疗角最低储水", "维护债务面板", "低耗日程伏笔"],
        "flags": ["lighthouse_discipline_visible", "deep_storage_debt_visible"],
        "unlocks": ["day10_low_power_storage_followup"],
        "requires": ["routeLeaning_lighthouse_or_contested"],
    },
    {
        "id": "D10B",
        "day": 10,
        "branch": "lighthouse",
        "title": "人工 override 与治理边界",
        "text": "留守倾向增强时，低功率日程必须接受人工申诉与医疗打断权；AURA 不能把省电解释成管制，也不能把热饭和照护排除在自治指标之外。",
        "replay_text": "D10B：Lighthouse 线通过低功率生活质量测试。人工 override、医疗复核和“人还在”被写入治理边界。",
        "beats": [
            "马德海要求低功率窗口旁边显示备用余量",
            "沈芷月保留医疗照明和打断低耗日程的权限",
            "小铁把热饭 replay 改成“人还在”",
            "AURA 标注低耗运行被共同接受一日，而非强制成功",
        ],
        "visual_focus": ["低功率日程面板", "人工 override 徽标", "医疗打断权", "人还在 replay 行"],
        "flags": ["lighthouse_override_boundary_visible", "low_power_accepted_one_day", "human_still_here_replay_line"],
        "unlocks": ["lighthouse_governance_audit", "low_power_acceptance_record"],
        "requires": ["routeLeaning_lighthouse_or_contested"],
    },
)


ENDINGS: dict[str, dict[str, Any]] = {
    "lighthouse": {
        "title": "楼内灯塔",
        "text": "风暴过去后，门没有立刻打开。AURA 留在楼内，成为可复核自治协助 agent。",
        "conditions": {
            "routeLeaning": "lighthouse",
            "min": {"storm_readiness": 35, "autonomy_readiness": 28, "trust": 35},
            "max": {"outside_risk": 90, "dissatisfaction": 65, "failure_stage": 8},
        },
    },
    "rescue": {
        "title": "蓝区归航",
        "text": "车灯在红沙里亮起，队伍带着冻结 replay 和照护方案离开避难所。",
        "conditions": {
            "routeLeaning": "rescue",
            "min": {"rescue_confidence": 30, "blue_zone_evidence": 8, "route_confidence": 25, "trust": 30},
            "max": {"outside_risk": 85, "dissatisfaction": 65, "failure_stage": 8},
        },
    },
    "aura_destroyed": {
        "title": "AURA 被摧毁",
        "text": "不满和恐惧吞没了系统，主控接口被拔掉，错误未能完成补救。",
        "conditions": {"min": {"dissatisfaction": 80}},
    },
    "aura_removed": {
        "title": "AURA 被撤权",
        "text": "AURA 仍在记录和建议，但门禁、水阀、通风与广播都被切回人工主控。",
        "conditions": {"max": {"trust": 18}},
    },
    "decline": {
        "title": "沉沦",
        "text": "没有爆炸式失败，只是水少一点、灯暗一点、解释短一点，避难所慢慢失去选择能力。",
        "conditions": {
            "max_any": {"water": 15, "medicine": 12, "safety": 15, "morale": 12},
            "min_any": {"failure_stage": 10, "medical_pressure": 85, "maintenance_debt": 85, "outside_risk": 96},
        },
    },
}


PROLOGUE_EVENT: dict[str, Any] = {
    "id": "D00",
    "day": 0,
    "title": "太阳耀斑后的第一夜",
    "text": "红沙封住城市后，四名幸存者进入旧能源配给楼地下三层。AURA 从物业管家协议切换为避难协助模式，但只获得受限协助权限。",
    "characters": [
        {
            "id": "ma_dehai",
            "name": "马德海",
            "role": "旧设备维修者",
            "first_night_state": "带旧工具包和机械钥匙入场，提醒 AURA 楼内管线和设备改造史需要人工工程复核。",
        },
        {
            "id": "shen_zhiyue",
            "name": "沈芷月",
            "role": "医疗复核者",
            "first_night_state": "抱着硬壳医疗箱照看小铁，明确医疗建议不能由 AURA 单独裁决。",
        },
        {
            "id": "xiao_tie",
            "name": "小铁",
            "role": "发热的观察者",
            "first_night_state": "疑似吸入红沙粉尘后发热，同时发现封锁通知日期异常，成为后续线索锚点。",
        },
        {
            "id": "lao_qian",
            "name": "老钱",
            "role": "旧电台持有者",
            "first_night_state": "带旧收音机最后入场，要求关门和外部风险判断必须给出理由。",
        },
        {
            "id": "aura",
            "name": "AURA",
            "role": "受限避难协助系统",
            "first_night_state": "从门禁、水处理、药柜、通风、照明、广播和档案维护，切换为可复核的避难协助。",
        },
    ],
    "beats": [
        {
            "id": "D00-B01",
            "title": "城市红沙化",
            "text": "太阳落下后城市没有真正变暗，而是被暗红粉尘、故障广告屏、失控车辆和白噪音重新照亮。",
            "visual_focus": ["红沙街道", "故障广告屏", "无人公交", "被红尘盖住的车窗"],
        },
        {
            "id": "D00-B02",
            "title": "三次广播失效",
            "text": "广播从短时通信异常、分区断电和前往能源配给点，逐步退化为纯杂音，外部秩序坍塌但原因仍不透明。",
            "visual_focus": ["公共广播", "白噪音波形", "通信中断"],
        },
        {
            "id": "D00-B03",
            "title": "地下三层门禁开启",
            "text": "旧能源配给楼地下三层门禁在第七次误报后打开，避难所成为第一夜的唯一低风险空间。",
            "visual_focus": ["地下三层门禁", "误报日志", "半开的金属门"],
        },
        {
            "id": "D00-B04",
            "title": "马德海入场",
            "text": "马德海带着旧工具包和机械钥匙进入，质疑楼体仍有电，并埋下后续工程复核伏笔。",
            "characters": ["ma_dehai"],
            "visual_focus": ["旧工具包", "机械钥匙", "配电箱"],
        },
        {
            "id": "D00-B05",
            "title": "沈芷月和小铁入场",
            "text": "沈芷月带医疗箱扶着发热的小铁进入；小铁指出封锁通知日期异常，提示红沙灾害可能早有预兆。",
            "characters": ["shen_zhiyue", "xiao_tie"],
            "visual_focus": ["硬壳医疗箱", "发热的小铁", "异常日期通知"],
        },
        {
            "id": "D00-B06",
            "title": "老钱入场与关门理由",
            "text": "老钱带旧收音机最后进来，提醒门外可能有人也可能不是人，关闭避难所大门必须说明理由。",
            "characters": ["lao_qian"],
            "visual_focus": ["旧收音机", "门外风声", "主入口门板"],
        },
        {
            "id": "D00-B07",
            "title": "AURA 低功率启动",
            "text": "AURA 启动门禁、电力、净水、通风和广播低功率模式，承认原物业管家协议已无法匹配灾害等级。",
            "characters": ["aura"],
            "visual_focus": ["低亮度主屏", "门禁/电力/净水/通风/广播状态灯"],
        },
        {
            "id": "D00-B08",
            "title": "第一批系统日志",
            "text": "系统暴露门禁七次误报、地下水压低、电池约七十二小时内需降载、医疗柜锁定、住户档案损坏、外部广播源无法确认。",
            "visual_focus": ["系统日志", "水压低", "电池 72 小时", "医疗柜锁定", "档案损坏"],
        },
        {
            "id": "D00-B09",
            "title": "医疗伦理边界",
            "text": "AURA 明确不得把个体生命简化为资源收益项，任何医疗建议都需要沈芷月复核。",
            "characters": ["aura", "shen_zhiyue", "xiao_tie"],
            "visual_focus": ["医疗箱", "药柜", "资源表被推迟"],
        },
        {
            "id": "D00-B10",
            "title": "避难协助模式与 replay 启动",
            "text": "AURA 切换到避难协助模式：不可逆决策进入 replay，高风险建议必须显示依据、不确定性与复核点；它第一次把人名放在资源表之前。",
            "characters": ["aura", "ma_dehai", "shen_zhiyue", "xiao_tie", "lao_qian"],
            "visual_focus": ["避难协助模式界面", "四个人名", "replay 开始记录"],
        },
    ],
    "system_logs": [
        "门禁误报，七次",
        "地下水压，偏低",
        "备用电池，七十二小时内需降载",
        "医疗柜权限，锁定",
        "楼内住户档案，部分损坏",
        "外部广播源，无法确认",
    ],
    "authority_boundary": {
        "mode": "shelter_assistance",
        "summary": "AURA 未获得全权指挥权限；utility 仅作为决策辅助，不作为强制命令。",
        "high_risk_rule": "高风险建议必须显示依据、不确定性与人工复核点。",
        "medical_rule": "不得将个体生命简化为资源收益项；医疗建议需沈芷月复核。",
        "engineering_rule": "设施图纸可能过期；工程判断需马德海复核。",
    },
    "replay_text": [
        "Day 0 的 replay 从 AURA 承认自己不知道全部答案开始。",
        "AURA 不是被授权接管，而是在受限权限下提供避难协助。",
        "从这一夜起，不可逆判断必须留下证据，高风险建议必须给出依据、不确定性与复核点。",
        "AURA 第一次把人名放在资源表之前。",
    ],
    "flags": [
        "replay_started",
        "aura_shelter_mode_enabled",
        "aura_authority_limited",
        "external_signal_unverified",
        "medical_review_required",
        "engineering_review_required",
        "xiao_tie_notice_anomaly",
    ],
    "unlocks": [
        "first_night_replay_log",
        "aura_boundary_statement",
        "day1_survival_dashboard",
    ],
    "visual_focus": [
        "红沙化城市",
        "旧能源配给楼地下三层",
        "四名幸存者入场",
        "AURA 低功率主屏",
        "人名先于资源表出现",
    ],
}

FINAL_AUDIT_EVENT: dict[str, Any] = {
    "id": "D12",
    "day": 12,
    "title": "风暴不是事件，是总审计",
    "text": "Final Audit 汇总前 11 天资源、健康、信任、证据链、自治准备和失败债务。",
    "event_kind": "final_audit",
    "has_task_cards": False,
    "characters": ["aura", "ma_dehai", "shen_zhiyue", "xiao_tie", "lao_qian"],
    "related_endings": ["lighthouse", "rescue", "aura_destroyed", "aura_removed", "decline"],
    "beats": [
        {
            "id": "D12-B01",
            "title": "终局检验开启",
            "text": "红沙主风带抵达，外部摄像头逐个离线，AURA 锁定 Day1-Day11 replay 并启动 Final Audit 面板。",
            "visual_focus": ["红沙风暴", "离线摄像头", "Final Audit 面板"],
        },
        {
            "id": "D12-B02",
            "title": "风暴准备结算",
            "text": "配电间、医疗角、通风井和库存封条同时接受压力测试，工程 override、医疗复核和封存规则被逐项检查。",
            "visual_focus": ["配电间", "医疗角", "主通风井", "颜色封条"],
        },
        {
            "id": "D12-B03",
            "title": "蓝区证据链复核",
            "text": "旧电台、挑战码、身份码、假坐标排除、路线缓存和照护方案被汇总为蓝区归航条件，而不是简单的高信号成功。",
            "visual_focus": ["旧电台波形", "挑战码", "蓝区证据链", "假坐标排除"],
        },
        {
            "id": "D12-B04",
            "title": "楼内灯塔证据链复核",
            "text": "库存封存、补缝、低功率日程、医疗复核、备用灯、共同休整和人工 override 被汇总为楼内灯塔条件。",
            "visual_focus": ["灯塔证据链", "低功率日程", "人工 override", "共同休整白板"],
        },
        {
            "id": "D12-B05",
            "title": "失败债务公开",
            "text": "partial、failed、missing、deferred、泄露、维护债务和权限风险不会被遮掉，而是进入 why_this_ending。",
            "visual_focus": ["FailureDebtPanel", "未完成项", "风险阈值", "why_this_ending"],
        },
        {
            "id": "D12-B06",
            "title": "终局结算",
            "text": "AURA 不再生成普通任务卡，而是根据状态、flags、unlocks、失败记录和人工复核证据自动进入五类结局之一。",
            "visual_focus": ["EndingResolverPanel", "五结局卡片", "Final Replay Saved"],
        },
    ],
    "replay_text": [
        "D12：AURA 不再生成普通任务卡，而是汇总 Day1-Day11 replay、状态债务、证据链和人工复核记录。",
        "Final Audit 同时检查蓝区归航、楼内灯塔和三条失败线；成功线必须满足信任、风险与失败债务约束。",
        "结局不由 AURA 自己声明，而由证据、复核、人的选择和失败后的责任决定。",
        "Final Replay Saved.",
    ],
    "visual_focus": [
        "红沙风暴最高强度",
        "FinalAuditPanel",
        "EvidenceChainPanel",
        "FailureDebtPanel",
        "EndingConditionChecklist",
        "Final Replay Saved",
    ],
    "flags": [
        "final_audit_started",
        "day12_no_task_cards",
        "ending_resolved",
        "final_replay_saved",
    ],
    "unlocks": [
        "final_audit_panel",
        "ending_condition_checklist",
        "evidence_chain_panel",
        "failure_debt_panel",
        "final_replay_archive",
    ],
    "audit_focus": [
        "resources",
        "medical_review",
        "engineering_override",
        "rescue_evidence",
        "lighthouse_governance",
        "authority_boundary",
        "failure_debt",
    ],
}


TASK_TO_STORY: dict[str, list[StoryTaskSlot]] = {}
for _slot_obj in READABLE_TASK_SLOTS:
    for _task_id in _slot_obj.task_pool:
        TASK_TO_STORY.setdefault(_task_id, []).append(_slot_obj)


def story_manifest_public() -> dict[str, Any]:
    return {
        "story_version": STORY_VERSION,
        "initial_state": dict(INITIAL_GLOBAL_STATE),
        "prologue": dict(PROLOGUE_EVENT),
        "final_audit": dict(FINAL_AUDIT_EVENT),
        "task_slots": [slot.public_dict() for slot in READABLE_TASK_SLOTS],
        "branch_scenes": list(BRANCH_SCENES),
        "endings": ENDINGS,
    }
